### ISSUE TITLE
New issue for Williams Lab

### ISSUE THREAD

**Issue by isazar** [Openscapes/css-cohort#3]
isa is trying to use the **Issues**

**Comment by ognancy4life** [comment]
@sbartoloni can you please take care of this!?

**Comment by vtamsitt** [comment]
hi @isazar @ognancy4life

**Comment by jules32** [comment]
tagging @isazar :)

**Comment by sbartoloni** [comment]
> @sbartoloni can you please take care of this!?

Yes!

**Comment by isazar** [comment]
> hi @isazar @ognancy4life

_replying to V_

**Comment by vtamsitt** [comment]
### this is a header
**this is bold**
_this is italics_

> it's a quote!

here's some code:
`import numpy as np`

Tasks

- [ ] fix the issue
- [x] write an issue
- [x] yay

**Comment by vtamsitt** [comment]
> > hi @isazar @ognancy4life
> 
> _replying to V_

hi Isa!

**Comment by isazar** [comment]
> tagging @isazar :)

ha! tagging @jules32 back :)

**Comment by isazar** [comment]
> ### this is a header
> 
> **this is bold**
> _this is italics_
> 
> > it's a quote!
> 
> here's some code:
> `import numpy as np`
> 
> Tasks
> 
>     * [ ]  fix the issue
> 
>     * [x]  write an issue
> 
>     * [x]  yay

Tagging a different issue:
#1

**Comment by isazar** [comment]
> > > hi @isazar @ognancy4life
> > 
> > 
> > _replying to V_
> 
> hi Isa!

### Hi V!!! 👯
